# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NAS FAQ
tagline:          'NAS FAQ'
description:      'Site with FAQ relative to self made NAS.'
url:              http://nas-faq.nas-faq.com
baseurl:          /

paginate:         1

github:
  repo:           https://github.com/nas-faq/nas-faq.github.io

gems:
  - jekyll-sitemap
