# Site settings
title: NAS FAQ
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Сайт о создании NAS своими руками
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nas-faq.nas-faq.com" # the base hostname & protocol for your site
#twitter_username: nas-faq
github_username:  nas-faq/nas-faq.github.io
# --------- our settings -------------------------------------------------------
current_forum: http://forum.ixbt.com/topic.cgi?id=109:82
toc_name: Содержание

######### Build settings #########
markdown: redcarpet
redcarpet:
  # enable auto ids for redcarpet
  extensions: 
    # - with_toc_data <- Not necessary, because we use JavaScript to make TOC on the fly.
    - autolink # converts links in text in a real links in the HTML
    - no_intra_emphasis
    - strikethrough
    - superscript

gems:
  - jekyll-sitemap
  - jemoji